// Auto-generated by xi-engine.py export-state
// 2026-03-04T08:01:20.194770+00:00
const XI_STATE = {
  "xi_dismiss_brief-20260303-test": {
    "status": "complete",
    "timestamp": "2026-03-04T08:01:11.355794+00:00",
    "summary": "Dismissed: brief-20260303-test",
    "action": "dismiss"
  },
  "xi_dive_DoctorPerin": {
    "status": "pending",
    "timestamp": "2026-03-04T08:01:17.157045+00:00",
    "summary": "",
    "action": "dive"
  }
};
const XI_FEEDBACK = {
  "signal": 0,
  "noise": 0,
  "dismissed": 1
};
